config/routes.rb
VcesteTuit::Application.routes.draw do

  ActiveAdmin.routes(self)
  
  root :to => 'timelines#index'

  devise_for :users, :controllers => { :sessions => "users/sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :timelines

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  after_create :lowercase
  validates :hashtag,
  :presence   => true,
  :format     => { :with => /#\S*/ }

  def to_param
    "#{hashtag.gsub("#", "")}".parameterize
  end
  
  def lowercase
  	self.hashtag = self.hashtag.downcase
  	save
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @timelines = Timeline.all
    gon.where = "home"
    render :layout => false
  end


  def show
  	if (params[:save] == "true")
  	  unless Timeline.exists?(hashtag: "##{params[:id]}")
  	    Timeline.create(:hashtag => "##{params[:id]}") 
  	  end
  	end
  	if Timeline.exists?(hashtag: "##{params[:id]}")
      @timeline = Timeline.find_by_hashtag("##{params[:id]}")
    else
      @timeline = Timeline.find_by_id(params[:id])
  	end
    gon.hashtag = @timeline.hashtag
  end

  def create
  	unless Timeline.exists?(hashtag: params[:hashtag])
  	  t = Timeline.create!(:hashtag => params[:hashtag])
  	else
  	  t = Timeline.find_by_hashtag(params[:hashtag])
  	end
  	redirect_to timeline_path(t)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social Scream!</title>
  <%= include_gon %>
  <%= analytics_init if Rails.env.production? %>
  
  
  <%= csrf_meta_tags %>
  <%= yield :meta %>
</head>
<body>

<%= yield %>

</body>
<%= javascript_include_tag "application" %>
</html>

app/views/timelines/index.html.haml
= stylesheet_link_tag "home"

.navbar.navbar-fixed-top
  .navbar-inner
    .container
      / # = link_to("Social Screen", "/", class: "brand")
.container
  .hero-unit
    %h1 Social Scream v0.1
    %p 
      Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.
    %p
      = form_tag(timelines_path, method: 'post', class: "form-search") do
        = text_field_tag 'hashtag', nil, :placeholder => 'Enter hashtag here...', class: "input-primary input-large search-query", id: "hashtag-main-input"
        = submit_tag "Hold on to your butts", class: "btn btn-primary btn-large"
  .row
    .span4
      %h2 Available Screams
      %p
      - times = Timeline.all
      - times.each do |t|
        =link_to( t.hashtag, t)

      %p
        
    .span4
      %h2 I'm serious as a heart attack
      %p
        You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.
    .span4
      %h2 No man, I don't eat pork
      %p
        My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

  %hr
  .footer
    .p
      © Deliens Dev
  = javascript_include_tag "home"

app/views/timelines/show.html.haml
= stylesheet_link_tag "application"
%body{:class => "white impress-not-supported" }

  #hashtag

  #impress

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>